### ISSUE TITLE
Get SQLAlchemy to see existing tables from MySQL

### ISSUE THREAD

**Issue by michaelsilver** [infolab-csail/wikithingsdb#3]
I'm having trouble getting SQLAlchemy to see the existing tables `page` and `redirect` tables on Malta's MySQL DB. This is important because relationship tables `article_types` and `article_classes` use `page`'s `page.page_id` as a Foreign Key. This is also important because I would like to use SQLAlchemy to get the relationship in `redirect` that shows what are the titles of redirect pages for a certain page, again using `page` Foreign Keys (as Chris shows [here](https://projects.csail.mit.edu/cgi-bin/wiki/view/Infolab/WikipediaBase#Get_synonyms_from_redirects)).

You can see full versions of my two different attempts to use [automap](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/automap.html?highlight=automap#module-sqlalchemy.ext.automap) (see e369b8edbee5565a3c0222d834b8343c96c0634d) and [reflection](http://docs.sqlalchemy.org/en/rel_1_0/core/reflection.html) (see 9d2bd6641ff75726e42a014d5b609d11635613a5) in the `models` branch. Each time I still get the same error that I reported in commit 12ba51447e6b32887295020e1670b1b7e66bfa5d. Maybe it's some silly bug or something, but I'm really stuck.

Help?

**Comment by alvaromorales** [comment]
Huh, I really can't figure this out. Automap is not loading the `page` table by the time the `article_classes` table is created. I'll keep looking at this, maybe I'll have better luck tomorrow.

In the meantime: what if you avoid using automap or reflection, and define a `Page` class that matches the schema of the `page` table. SQLAlchemy should be able to find the `page_id`, I hope.

This approach may be desirable anyway because you're being explicit by defining the schema of the table. You can look at the schema using `mysql> describe page;`.

**Comment by alvaromorales** [comment]
Did it work?

**Comment by michaelsilver** [comment]
Looks like it -- no errors on creation, and the schemata look perfect. Will see when I try to fetch data from the DB.

**Comment by alvaromorales** [comment]
:+1: excellent! :tada:
